# This file was generated by GoReleaser. DO NOT EDIT.
class Marco < Formula
  desc "Marco is a CLI tool for showing Spinnaker application, pipelines and pipeline templates"
  homepage "https://github.com/kekeniker/marco"
  version "0.0.4"
  bottle :unneeded

  if OS.mac?
    url "http://github.com/kekeniker/marco/releases/downloads/v0.0.4/marco_0.0.4_darwin_amd64.tar.gz"
    sha256 "47b4137abfedb635a88af19a425ea40d4acc0e2328f2ad19abe945a2ead39693"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "http://github.com/kekeniker/marco/releases/downloads/v0.0.4/marco_0.0.4_linux_amd64.tar.gz"
    sha256 "6bca993152eb6d468b409f916fe8bd7de89bb32b610bd5907b2fcad5d530c154"
  end

  def install
    bin.install "marco"
  end

  test do
    system "#{bin}/marco --version"
  end
end
