# This file was generated by GoReleaser. DO NOT EDIT.
class Spa < Formula
  desc "Spinnaker Admin tools"
  homepage "https://github.com/kekeniker/spa"
  version "0.0.2"
  bottle :unneeded

  if OS.mac?
    url "http://github.com/kekeniker/spa/releases/v0.0.2/spa_0.0.2_darwin_amd64.tar.gz"
    sha256 "a3b4a0c92545d4d84c48eed22b10f82ab25edb74fdd1c5352118733ef3c8a975"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "http://github.com/kekeniker/spa/releases/v0.0.2/spa_0.0.2_linux_amd64.tar.gz"
    sha256 "cab5c28e83f8a59035fd79ec005ac93b60cbcc0270ced49880896d660b4af4d2"
  end

  def install
    bin.install "spa"
  end

  test do
    system "#{bin}/spa --version"
  end
end
