# This file was generated by GoReleaser. DO NOT EDIT.
class Spa < Formula
  desc "Spinnaker Admin tools"
  homepage "https://github.com/kekeniker/spa"
  version "0.0.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/kekeniker/spa/releases/download/v0.0.4/spa_0.0.4_darwin_amd64.tar.gz"
    sha256 "ccb391c53f6d318405e6ecdde4d22eb009b62fb91ad70c660610b70322374610"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/kekeniker/spa/releases/download/v0.0.4/spa_0.0.4_linux_amd64.tar.gz"
    sha256 "2171b94b95a711529884beeed2a03a7ce72c99ea4f78601b93dbfe22447064b0"
  end

  def install
    bin.install "spa"
  end

  test do
    system "#{bin}/spa --version"
  end
end
