# This file was generated by GoReleaser. DO NOT EDIT.
class Marco < Formula
  desc "Marco is a CLI tool for showing Spinnaker application, pipelines and pipeline templates"
  homepage "https://github.com/kekeniker/marco"
  version "0.0.1"
  bottle :unneeded

  if OS.mac?
    url "http://github.mycompany.com/foo/bar/releases/v0.0.1/marco_0.0.1_darwin_amd64.tar.gz", :using => CurlDownloadStrategy.
    sha256 "2bf9a39631d995f1117fc62cad1dee5629660fbee0d5034fb55dba4ef8746b49"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "http://github.mycompany.com/foo/bar/releases/v0.0.1/marco_0.0.1_linux_amd64.tar.gz", :using => CurlDownloadStrategy.
    sha256 "7b2a41f356ba3bca229138c482c543566eeea0c4f2c078f931758df607ebffda"
  end

  def install
    bin.install "marco"
  end

  test do
    system "#{bin}/marco --version"
  end
end
